//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public short active { get; set; }
        public string description { get; set; }
        public string source_address { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string bo_type { get; set; }
        public Nullable<byte> permissions { get; set; }
        public Nullable<System.Guid> key { get; set; }
    }
}
